### ISSUE TITLE
Included Mapcode C library out of date

### ISSUE THREAD

**Issue by rijnb** [matlads/mapcode-postgres#2]
Hi, the included mapcode C library is version 1.40 from 2 years ago. 
We have since provided a couple of major updates to the library.
The latest version is 2.2., https://github.com/mapcode-foundation/mapcode-cpp/releases/tag/v2.2.1

The changes since 1.40 include:
- a number of bug fixes and enhancements for a number of countries
- support for high precision extensions (up to nm accuracy)
- significant performance improvements
- improved handling for different scripts (alphabets)

Note that most mapcodes from 1.40 are still valid in the new release, but some mapcodes are no longer valid or supported (in particular Antartica AT0-8 codes). 

We would like to suggest you include the latest version of the mapcode library to profit from these enhancements.

Happy coding and kind regards,
Rijn Buve (from the Mapcode Foundation)

**Comment by matlads** [comment]
Fixed in v.0.0.4
